#! /bin/bash

#####################################
# previous coding by: crimsonmane   #
# github.com/crimsonmane/nightshade #
#         revised 20140109          #
#####################################

# DEFINE COMMON FUNCTIONS
title(){ printf '%s\n%s - %s\n%s\n' "$title2" "$title1" "$1" "$title2"; }

notice(){ printf '%s\n' "$@"; }

shareLink(){
  text=" Share this URL with your helper! "
  line="--------------------------------------"
  printf '\nData collection in progress - please wait...\n'
  printf '%s\nvv%svv\n%s\n' "$line" "$text" "$line"
  eval "$1"
  printf '%s\n^^%s^^\n%s\n' "$line" "$text" "$line"
}

# DEFINE TROUBLESHOOTER - AUDIO
audio(){
  #clear
  title "Troubleshoot Audio"
  select item in "Do Nothing" "The only audio device shown is Dummy Output"
  do
    case $item in
      "The only audio device shown is Dummy Output")
	sudo aptitude purge --safe-resolver alsa-base pulseaudio
	sudo aptitude install -y alsa-base pulseaudio
	sudo alsa force-reload
	notice "Changes will take effect when you reboot. Please reboot."
	break;;
      "Same as #2 but that fix didn't work.")
	notice "Section not written."
	break;;
      *)
	break;;
    esac
  done
}

# DEFINE TROUBLESHOOTER - VIDEO
video(){
  #clear
  title "Troubleshoot Video"
  select item in "Do Nothing" "I have Optimus Intel/NVIDIA hybrid graphics card and need Bumblebee."
  do
    case $item in
      "I have Optimus Intel/NVIDIA hybrid graphics card and need Bumblebee.")
	bumblebeeInstall
	break;;
      *)
	break;;
    esac
  done
}

#DEFINE BUMBLEBEE INSTALLER
bumblebeeInstall(){
  sudo apt-add-repository ppa:bumblebee/stable
  case $mintVersion in
    *"Mint 16"*)
      version="saucy"
      file="/etc/apt/sources.list"
      break;;
    *"Mint 15"*)
      version="raring"
      file="/etc/apt/sources.list"
      break;;
    *"Mint 14"*)
      version="quantal"
      file="/etc/apt/sources.list"
      break;;
    *"Mint 13"*)
      version="precise"
      file="/etc/apt/sources.list"
      break;;
    *)
      notice "Ferret does not support your version. Please report an issue."
      sleep 4
      file="/dev/null"
      break;;
  esac
  line1="deb http://archive.ubuntu.com/ubuntu/ $version main restricted universe multiverse"
  line2="deb http://archive.ubuntu.com/ubuntu/ $version-updates main restricted universe multiverse"
  line3="deb http://security.ubuntu.com/ubuntu/ $version-security main restricted universe multiverse"
  line0="The following three lines were added by Ferret, as user requested to install Bumblebee for Optimus Intel/NVIDIA."
  if $file != "/dev/null"
  then
    sudo echo $line0 >> $file
    sudo echo $line1 >> $file
    sudo echo $line2 >> $file
    sudo echo $line3 >> $file
    sudo aptitude update
    case $mintVersion in
      *"Mint 16"*)
	sudo aptitude install -y bumblebee bumblebee-nvidia primus linux-headers-generic
	break;;
      *)
	sudo aptitude install -y bumblebee bumblebee-nvidia virtualgl linux-headers-generic
	break;;
    esac
  fi
  notice "A reboot is required for changes to take effect."
}

# DEFINE TROUBLESHOOTER - WIFI
wifi(){
  case $(inxi -Nxx) in
    *"BCM43"*)
      notice "Found BCM43xx WiFi card. Enter password to install drivers or CTRL+C to skip."
      sudo aptitude install firmware-b43-installer
      ;;
    *)
      notice "No wifi issues detected. If an issue does exist please report a flaw."
      ;;
  esac
}

# POPULAR SOFTWARE SECTION
ps3ms(){
  #clear
  title "PS3 Media Server"
  select item in "Install" "Remove" "Do Nothing"
  do
    case $item in
      "Install")
	sudo apt-add-repository ppa:happy-neko/ps3mediaserver
	sudo aptitude update
	sudo aptitude install ps3mediaserver
	break;;
      "Remove")
	sudo aptitude purge -y ps3mediaserver
	sudo apt-add-repository --remove ppa:happy-neko/ps3mediaserver
	break;;
      *)
	break;;
    esac
  done
}

plex(){
  #clear
  title "Plex Media Server"
  select item in "Install" "Remove" "Do Nothing"
  do
    case $item in
      "Install")
	firefox http://www.plexapp.com/getplex/
	break;;
      "Remove")
	sudo aptitude purge -y plexmediaserver
	break;;
      *)
	break;;
    esac
  done
}

wine(){
  #clear
  title "Wine"
  select item in "Install" "Remove" "Do Nothing"
  do
    case $item in
      "Install")
        sudo apt-add-repository ppa:ubuntu-wine/ppa
        sudo aptitude update
        apt-cache search wine
        notice "It's your job to 'sudo apt-get install <package>' depending on which version of wine you're after. Versions ending in odd numbers are considered unstable, while even ones are considered stable. World of Warcraft players will want the latest version regardless."
        break;;
      "Remove")
        sudo aptitude purge -y wine*
        sudo apt-add-repository --remove ppa:ubuntu-wine/ppa
        break;;
      *)
        break;;
    esac
  done
}

netflixDesktop(){
  #clear
  title "netflix-desktop"
  select item in "Install" "Remove" "Do Nothing"
  do
    case $item in
      "Install")
	if ! dpkg -l | grep pipelight-multi
	then
	  sudo apt-add-repository ppa:ehoover/compholio
	fi
	sudo aptitude update
	sudo aptitude install -y netflix-desktop
	break;;
      "Remove")
	sudo aptitude purge -y netflix-desktop
	if ! dpkg -l | grep pipelight-multi
	then
	  sudo apt-add-repository --remove ppa:ehoover/compholio
	fi
	break;;
      *)
	break;;
    esac
  done
}

pipelight(){
  #clear
  title "Netflix/Pipelight"
  select item in "Install" "Remove" "Do Nothing"
  do
    case $item in
      "Install")
	if ! dpkg -l | grep pipelight
	then
	  sudo aptitude purge pipelight
	fi
	if ! dpkg -l | grep netflix-desktop
	then
	  sudo apt-add-repository ppa:ehoover/compholio
	fi
	sudo apt-add-repository ppa:mqchael/pipelight
	sudo aptitude update
	sudo aptitude install pipelight-multi
	sudo pipelight-plugin --enable silverlight
	rm -rf ~/.wine-pipelight
	notice "*****************************************************************" "* Please install both firefox addons that are about to pop up.  *" "* Sometimes UAC doesn't work and you need to use the Overrider. *" "* It's up to you to play with these to get netflix.com to work. *" "* If your browser is open, please close it now.                 *" "* If firefox is not your desired browser, it's up to you to     *" "*                                get these addons yourself.     *" "*****************************************************************"
	read -n1 -r -p "Press any key to continue..."
	firefox https://addons.mozilla.org/en-US/firefox/addon/user-agent-overrider/ https://addons.mozilla.org/en-us/firefox/addon/uacontrol/
	break;;
      "Remove")
	sudo aptitude purge -y pipelight-multi
	sudo apt-add-repository --remove ppa:mqchael/pipelight
	if ! dpkg -l | grep netflix-desktop
	then
	  sudo apt-add-repository --remove ppa:ehoover/compholio
	fi
	break;;
      *)
	break;;
    esac
  done
}

handbrake(){
  #clear
  title "Handbrake"
  select item in "Install" "Remove" "Do Nothing"
  do
    case $item in
      "Install")
	sudo add-apt-repository ppa:stebbins/handbrake-releases
	sudo aptitude update
	sudo aptitude install -y handbrake-gtk handbrake-cli
	break;;
      "Remove")
	sudo aptitude purge -y handbrake-gtk handbrake-cli
	sudo apt-add-repository --remove ppa:stebbins/handbrake-releases
	break;;
      *)
	break;;
    esac
  done
}

chrome(){
  #clear
  title "Google Chrome"
  select item in "Install" "Remove" "Do Nothing"
  do
    case $item in
      "Install")
	wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
	sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/ferret-chrome.list'
	sudo aptitude update
	sudo aptitude install -y google-chrome-stable
	break;;
      "Remove")
	sudo aptitude purge -y google-chrome-stable
	sudo rm /etc/apt/sources.list.d/ferret-chrome.list
	break;;
      *)
	break;;
    esac
  done
}

bootRepair(){
  #clear
  title "Boot Repair"
  select item in "Install & Launch" "Remove" "Do Nothing"
  do
    case $item in
      "Install & Launch")
	if ! dpkg -l | grep boot-repair
	then
	  sudo apt-add-repository ppa:yannubuntu/boot-repair
	  sudo aptitude update
	  sudo aptitude install -y boot-repair
	fi
	boot-repair &
	break;;
      "Remove")
	sudo aptitude purge -y boot-repair
	sudo apt-add-repository --remove ppa:yannubuntu/boot-repair
	break;;
      *)
	break;;
    esac
  done
}

popularSoftware(){
  #clear
  title "Software Menu"
  select item in "Do Nothing" "Plex Media Server" "PS3 Media Server" "Wine" "Netflix-Desktop" "Netflix/Pipelight" "Google Chrome" "Handbrake"
  do
    case $item in
      "Do Nothing") item=-1; break;;
      "Plex Media Server") plex; break;;
      "PS3 Media Server") ps3ms; break;;
      "Netflix-Desktop") netflixDesktop; break;;
      "Netflix/Pipelight") pipelight; break;;
      "Google Chrome") chrome; break;;
      "Handbrake") handbrake; break;;
      "Wine") wine; break;;
    esac
  done
}

# DEFINE SNIFFERS
sniffSound(){
  inxi -Sc0 > temp.file
  inxi -Axc0 >> temp.file
  case $mintVersion in
    *"Mint 16"*)
      find ~/.config/pulse -name \*source\* -printf '\n\n%c\n%f\n' -execdir cat {} ';' >> temp.file
      ;;
    *)
      find ~/.pulse -name \*source\* -printf '\n\n%c\n%f\n' -execdir cat {} ';' >> temp.file
      ;;
  esac
  shareLink 'cat temp.file | pastebinit'
  rm temp.file
}

XorgLog(){
  shareLink "egrep -wi 'WW|EE' /var/log/Xorg.0.log | pastebinit"
}

syslog(){
  shareLink "{ inxi -c0 -FSRzdfulportcm20; egrep -i 'warn|error|critical' /var/log/syslog; } | pastebinit"
}

propDrivers(){
  case $mintVersion in
    *"KDE"*"Mint 13"*) jockey-kde;;
    *"KDE"*"Mint 14"*) software-properties-kde;;
    *"KDE"*"Mint 15"*) software-properties-kde;;
    *"Mint 13"*) jockey-gtk;;
    *"Mint 14"*) software-properties-gtk;;
    *"Mint 15"*) software-properties-gtk;;
    *"Mint 16"*) driver-manager;;
  esac
}

packageSearch(){
  notice "If you did not allow the routine updates when Ferret started, then these results are not going to be ideal. If that is the case, simply run Ferret again and allow updates."
  read -r -p "Type the package name you'd like to search: " pkg
  shareLink '{ echo "------installed------"; aptitude search -F "%p %V %v" "$pkg" | grep -iv none; echo "++++not installed++++"; aptitude search -F "%p %V %v" "$pkg" | grep -i none; } | pastebinit'
}

# DEFINE STARTUP ROUTINE
startup(){
# MOVE TO HOME FOLDER, PER WIKI DOWNLOAD INSTRUCTIONS
# THIS IS IN CASE USER CALLED FERRET FROM ANOTHER pwd
# AND EXPECTS THAT FERRET RESIDES WERE WIKI SAYS TO BE
  cd
# IF pastebinit NOT INSTALLED, INSTALL IT.
  notice "Checking if -pastebinit- is installed..." "Updating -inxi- in order to provide consistent output..." "Enter password to continue (because sudo is needed) or CTRL+C to skip" "(-inxi- updates often and so should you)..."
  if ! dpkg -l | grep pastebinit
  then
    sudo aptitude install pastebinit
  fi
# UPDATE inxi
  sudo inxi -U
# DO AUTOMATED CHECKS
  medibuntu
# DROP ELEVATED PRIVILEDGES. GIVES USER CHANCE TO READ NOTICES ON NEXT SUDO.
  sudo -k
}

# CHECK IF MEDIBUNTU EXISTS ON THIS SYSTEM. IF YES, REMOVE.
# ONLY NECESSARY PRIOR TO MINT 16.
medibuntu(){
  if inxi -r | grep -i medibuntu
  then
    notice "Medibuntu found in sources, causing update issues. Confirm removal by entering password (because sudo is needed), or CTRL+C to skip."
    if [ -a /etc/apt/sources.list.d/medibuntu* ]
    then
      sudo rm /etc/apt/sources.list.d/medibuntu*
    fi
      sudo cp /etc/apt/sources.list /etc/apt/sources.list.bkup
      sudo sed -i '/medibuntu/d' /etc/apt/sources.list
      notice "Medibuntu has been removed from sources. Confirm by running Update Manager."
    else
    notice "Medibuntu not found on this system. That's good!"
  fi
  sudo -k
}
# DEFINE UPDATE ROUTINE/METHOD
updateFerret(){
  wget https://raw.github.com/crimsonmane/nightshade/master/ferret -O ferret
  notice "Ferret is the newest version."
}

# DEFINE PRIMARY ROUTINE
main(){
    title "Main Menu"
    select item in "Do Nothing" "Update Ferret" "Popular Software" "Troubleshoot Audio" "Troubleshoot Video" "Troubleshoot WiFi" "sniff sound" "sniff Xorg log" "sniff syslog" "Package Search" "Launch Drivers Dialog" "Boot Repair"
    do
      case $item in
	"Do Nothing") item=-1; break;;
	"Update Ferret") updateFerret; break;;
	"Popular Software") popularSoftware; break;;
	"Troubleshoot Audio") audio; break;;
	"Troubleshoot Video") video; break;;
	"Troubleshoot WiFi") wifi; break;;
	"sniff sound") sniffSound; break;;
	"sniff Xorg log") XorgLog; break;;
	"sniff syslog") syslog; break;;
	"Package Search") packageSearch; break;;
	"Launch Drivers Dialog") propDrivers; break;;
	"Boot Repair") bootRepair; break;;
      esac
    done
# SHAMELESS MARKETING
  notice "Please 'like' my company page: https://facebook.com/nightshadePC"
# SHAMELESS BEGGING FOR CONTRIBUTIONS
  notice "Report flaws: https://github.com/crimsonmane/nightshade/issues"
# EXPRESS GENUINE GRATITUDE
  printf 'Thank you for using %s\n' "$title1!"
# DROP ELEVATED PRIVILEDGES. GIVES USER A CHANCE TO READ NOTICES ON NEXT SUDO.
  sudo -k
}

# RUN-ONCE ROUTINE
title1="Ferret (version 6)"
title2="------------------"
mintVersion=$(inxi -S)
startup
main

